language: node_js
cache: node_modules
node_js:
- '8'
- '7'
- '6'
before_install:
- npm install -g codecov
script:
- npm run lint
- npm run test -- --coverage
- codecov
before_deploy:
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- npm run release
- git push origin --tags
deploy:
  provider: npm
  email: nick@dobie.me
  api_key:
    secure: hRZltgdcX6+vAu/SlV/Y+DjATYCLDlHXmXmi8VUzvJKO5qumXUMdFsNe6KrW9tOEg0SLPaa3tAgKsS3b+qccouBrrXK+izyW8ALsE0CbbWHXazx0isdJR2zIB+S8eQ2KwKTJLMkzqSbPYik/1MAqaOTctJCadb0weYtYf81fHQYNDf2bvQA9Oki2M/WtL9TQFJrGkEhPgAqBPhIC8OFZVcvdqTil8C4X/Sfk8foP4hUz9X1OOwqIcb3O9jICvL9Q6dSmtuzc7QftK5HB7ObuXu8uiJUfOJXGc/4kehxJzNdcQhOcrhERTM2z2I7jQFpLcKgQ/UlKYrEJei8dBlTep6C8qgmERcnWxbLqKT7EMJ1G1wG9Y9gIBUEgNpdMwMHxIJHNVEYyBIwX09+lwoNVzFv0TSz+I4hqDRVCI+YOy+0X9NNIEvuvqlvGIZYGQjaS/PFRCaCf2z0ALXPS0N65zmcsgoNEo5a0ZOaCSCg/RGH71BWR7sNTgWutPvFetcX656eN6zhHkpw0DULOfrhtrTH7KPOzj8P2PAQk05gY4bgZOmIMAME3sY8VFW5yRXc3WxWDhkGIqofjKyLf/TFtd0jbKngGjubqTZ7TxYvG0alnQN9peP8OI/dxO8vz8UWmOY7AFeFtVcasVV/M5/YAVRxlusMzDAdQ1OBWzsvWgwg=
  on:
    branch: master
