language: node_js
cache: node_modules
node_js: 8
before_install:
- npm install -g codecov
script:
- npm run lint
- npm run test -- --coverage
- codecov
before_deploy:
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- npm run release
deploy:
  provider: npm
  email: nick@dobie.me
  api_key:
    secure: hRZltgdcX6+vAu/SlV/Y+DjATYCLDlHXmXmi8VUzvJKO5qumXUMdFsNe6KrW9tOEg0SLPaa3tAgKsS3b+qccouBrrXK+izyW8ALsE0CbbWHXazx0isdJR2zIB+S8eQ2KwKTJLMkzqSbPYik/1MAqaOTctJCadb0weYtYf81fHQYNDf2bvQA9Oki2M/WtL9TQFJrGkEhPgAqBPhIC8OFZVcvdqTil8C4X/Sfk8foP4hUz9X1OOwqIcb3O9jICvL9Q6dSmtuzc7QftK5HB7ObuXu8uiJUfOJXGc/4kehxJzNdcQhOcrhERTM2z2I7jQFpLcKgQ/UlKYrEJei8dBlTep6C8qgmERcnWxbLqKT7EMJ1G1wG9Y9gIBUEgNpdMwMHxIJHNVEYyBIwX09+lwoNVzFv0TSz+I4hqDRVCI+YOy+0X9NNIEvuvqlvGIZYGQjaS/PFRCaCf2z0ALXPS0N65zmcsgoNEo5a0ZOaCSCg/RGH71BWR7sNTgWutPvFetcX656eN6zhHkpw0DULOfrhtrTH7KPOzj8P2PAQk05gY4bgZOmIMAME3sY8VFW5yRXc3WxWDhkGIqofjKyLf/TFtd0jbKngGjubqTZ7TxYvG0alnQN9peP8OI/dxO8vz8UWmOY7AFeFtVcasVV/M5/YAVRxlusMzDAdQ1OBWzsvWgwg=
  skip_cleanup: true
  on:
    branch: master
after_deploy:
- git push https://nrdobie:$GITHUB_API_KEY@github.com/nrdobie/reserializer.git master
- git push https://nrdobie:$GITHUB_API_KEY@github.com/nrdobie/reserializer.git --tags
env:
  global:
    secure: iamYQQpdXf4zcgN2TQdXyqbYmpVGxq9ILttDhHeA4SjPhpS57hDL3ByJNr84PghZ9qBTzGIDF6hNOAsczsdRiCMY9nc/hebL+QeH7hk+c6z8VEPNXq1fcO3otuJlmJPaWHXhC1P2x0KIL7boUKrS0C4P9awAh51XwRrdOgeQvrGqQhsqg/vz3JQ0S8CWcdxViTPT8Iamm+vVpAVZhXWcB+xB+YbIb8ZRw4OyxGI31QnL7jp0D1JTzAHtL/nAZ6dpi55WoIXtQmnHQ5yE1VGzB9OrgiaGrMF2PRuBiPTZty4skAd8pa4CzwpFs7InxaBNDu3Te9V2+9rjxRa1vrBW/xokXVlSzUo3+b143cutoTLF0Yu9K+nXk+ZR3RsaBlzc36HYof8EhMQtUn4VL2bV6ADHbREbyU+gVSAsUVOu8jkiVduHu0hrLRmQRW92CQO4JQ+6ECrkkOnDsm6Ck5DBHCj9PwwrjWmwIMFdOjK4rPvSJcKfcg2UUr+YYTzaj5243Kt9yz9XyTSipyc2c35bv4vh54f5c2p+xCoJzdTNAQlspCO4huN7NQ9X6FQqlLVIdPWr0XKPTpUhzhxKU59JN/4ZRuDZpoAK8yL2IJX+6neKxpHfLVfvcupxIt1lbV5MZvAplhfZ1IEP3hZX2Osq6uSWF4xsBWOi1jFrBYjPJ+g=
